version: "3.8"

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - 9000:9000
    networks:
      - sonarqube_net
    volumes:
      - h2db_volume:/opt/sonarqube/data
      - logs_volume:/opt/sonarqube/logs
      - ext_volume:/opt/sonarqube/extensions
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

volumes:
  h2db_volume:
  logs_volume:
  ext_volume:

networks:
  sonarqube_net:
    driver: bridge
